/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTimetablesRouteImport } from './routes/_authenticated/timetables'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedMajorSectionsRouteImport } from './routes/_authenticated/major-sections'
import { Route as AuthenticatedCodesRouteImport } from './routes/_authenticated/codes'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedTimetableChangeRequestsIndexRouteImport } from './routes/_authenticated/timetable-change-requests/index'
import { Route as AuthenticatedTimetablesNewRouteImport } from './routes/_authenticated/timetables/new'
import { Route as AuthenticatedTimetablesCombineRouteImport } from './routes/_authenticated/timetables/combine'
import { Route as AuthenticatedTimetableChangeRequestsIdRouteImport } from './routes/_authenticated/timetable-change-requests/$id'
import { Route as AuthenticatedTeachersWelcomeRouteImport } from './routes/_authenticated/teachers/welcome'
import { Route as AuthenticatedTeachersNewRouteImport } from './routes/_authenticated/teachers/new'
import { Route as AuthenticatedSubjectsNewRouteImport } from './routes/_authenticated/subjects/new'
import { Route as AuthenticatedStudentsWelcomeRouteImport } from './routes/_authenticated/students/welcome'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students/new'
import { Route as AuthenticatedRoomsNewRouteImport } from './routes/_authenticated/rooms/new'
import { Route as AuthenticatedMajorSectionsNewRouteImport } from './routes/_authenticated/major-sections/new'
import { Route as AuthenticatedCodesNewRouteImport } from './routes/_authenticated/codes/new'
import { Route as AuthenticatedCodesIdRouteImport } from './routes/_authenticated/codes/$id'
import { Route as AuthenticatedAdminTimetablesRouteImport } from './routes/_authenticated/admin/timetables'
import { Route as AuthenticatedAdminTimetableChangeRequestsRouteImport } from './routes/_authenticated/admin/timetable-change-requests'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin/teachers'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin/subjects'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminRoomsRouteImport } from './routes/_authenticated/admin/rooms'
import { Route as AuthenticatedAdminMajorSectionsRouteImport } from './routes/_authenticated/admin/major-sections'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated/admin/codes'
import { Route as AuthenticatedTimetablesViewIdRouteImport } from './routes/_authenticated/timetables/view.$id'
import { Route as AuthenticatedTimetablesEditIdRouteImport } from './routes/_authenticated/timetables/edit.$id'
import { Route as AuthenticatedTeachersTimetableIdRouteImport } from './routes/_authenticated/teachers/timetable.$id'
import { Route as AuthenticatedTeachersEditIdRouteImport } from './routes/_authenticated/teachers/edit.$id'
import { Route as AuthenticatedSubjectsViewIdRouteImport } from './routes/_authenticated/subjects/view.$id'
import { Route as AuthenticatedSubjectsEditIdRouteImport } from './routes/_authenticated/subjects/edit.$id'
import { Route as AuthenticatedStudentsEditIdRouteImport } from './routes/_authenticated/students/edit.$id'
import { Route as AuthenticatedRoomsEditIdRouteImport } from './routes/_authenticated/rooms/edit.$id'
import { Route as AuthenticatedMajorSectionsEditIdRouteImport } from './routes/_authenticated/major-sections/edit.$id'
import { Route as AuthenticatedCodesEditIdRouteImport } from './routes/_authenticated/codes/edit.$id'
import { Route as AuthenticatedCodesIdValuesRouteImport } from './routes/_authenticated/codes/$id/values'
import { Route as AuthenticatedAdminTimetablesNewRouteImport } from './routes/_authenticated/admin/timetables/new'
import { Route as AuthenticatedAdminTeachersNewRouteImport } from './routes/_authenticated/admin/teachers/new'
import { Route as AuthenticatedAdminStudentsNewRouteImport } from './routes/_authenticated/admin/students/new'
import { Route as AuthenticatedAdminRoomsNewRouteImport } from './routes/_authenticated/admin/rooms/new'
import { Route as AuthenticatedCodesIdValuesNewRouteImport } from './routes/_authenticated/codes/$id/values/new'
import { Route as AuthenticatedCodesIdValuesEditValueIdRouteImport } from './routes/_authenticated/codes/$id/values/edit.$valueId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetablesRoute = AuthenticatedTimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMajorSectionsRoute =
  AuthenticatedMajorSectionsRouteImport.update({
    id: '/major-sections',
    path: '/major-sections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodesRoute = AuthenticatedCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimetableChangeRequestsIndexRoute =
  AuthenticatedTimetableChangeRequestsIndexRouteImport.update({
    id: '/timetable-change-requests/',
    path: '/timetable-change-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetablesNewRoute =
  AuthenticatedTimetablesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTimetablesRoute,
  } as any)
const AuthenticatedTimetablesCombineRoute =
  AuthenticatedTimetablesCombineRouteImport.update({
    id: '/combine',
    path: '/combine',
    getParentRoute: () => AuthenticatedTimetablesRoute,
  } as any)
const AuthenticatedTimetableChangeRequestsIdRoute =
  AuthenticatedTimetableChangeRequestsIdRouteImport.update({
    id: '/timetable-change-requests/$id',
    path: '/timetable-change-requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersWelcomeRoute =
  AuthenticatedTeachersWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedTeachersRoute,
  } as any)
const AuthenticatedTeachersNewRoute =
  AuthenticatedTeachersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTeachersRoute,
  } as any)
const AuthenticatedSubjectsNewRoute =
  AuthenticatedSubjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSubjectsRoute,
  } as any)
const AuthenticatedStudentsWelcomeRoute =
  AuthenticatedStudentsWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedRoomsNewRoute = AuthenticatedRoomsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoomsRoute,
} as any)
const AuthenticatedMajorSectionsNewRoute =
  AuthenticatedMajorSectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMajorSectionsRoute,
  } as any)
const AuthenticatedCodesNewRoute = AuthenticatedCodesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCodesRoute,
} as any)
const AuthenticatedCodesIdRoute = AuthenticatedCodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCodesRoute,
} as any)
const AuthenticatedAdminTimetablesRoute =
  AuthenticatedAdminTimetablesRouteImport.update({
    id: '/admin/timetables',
    path: '/admin/timetables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTimetableChangeRequestsRoute =
  AuthenticatedAdminTimetableChangeRequestsRouteImport.update({
    id: '/admin/timetable-change-requests',
    path: '/admin/timetable-change-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/admin/teachers',
    path: '/admin/teachers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/admin/subjects',
    path: '/admin/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoomsRoute = AuthenticatedAdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMajorSectionsRoute =
  AuthenticatedAdminMajorSectionsRouteImport.update({
    id: '/admin/major-sections',
    path: '/admin/major-sections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/admin/codes',
  path: '/admin/codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetablesViewIdRoute =
  AuthenticatedTimetablesViewIdRouteImport.update({
    id: '/view/$id',
    path: '/view/$id',
    getParentRoute: () => AuthenticatedTimetablesRoute,
  } as any)
const AuthenticatedTimetablesEditIdRoute =
  AuthenticatedTimetablesEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedTimetablesRoute,
  } as any)
const AuthenticatedTeachersTimetableIdRoute =
  AuthenticatedTeachersTimetableIdRouteImport.update({
    id: '/timetable/$id',
    path: '/timetable/$id',
    getParentRoute: () => AuthenticatedTeachersRoute,
  } as any)
const AuthenticatedTeachersEditIdRoute =
  AuthenticatedTeachersEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedTeachersRoute,
  } as any)
const AuthenticatedSubjectsViewIdRoute =
  AuthenticatedSubjectsViewIdRouteImport.update({
    id: '/view/$id',
    path: '/view/$id',
    getParentRoute: () => AuthenticatedSubjectsRoute,
  } as any)
const AuthenticatedSubjectsEditIdRoute =
  AuthenticatedSubjectsEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedSubjectsRoute,
  } as any)
const AuthenticatedStudentsEditIdRoute =
  AuthenticatedStudentsEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedRoomsEditIdRoute =
  AuthenticatedRoomsEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedRoomsRoute,
  } as any)
const AuthenticatedMajorSectionsEditIdRoute =
  AuthenticatedMajorSectionsEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedMajorSectionsRoute,
  } as any)
const AuthenticatedCodesEditIdRoute =
  AuthenticatedCodesEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedCodesRoute,
  } as any)
const AuthenticatedCodesIdValuesRoute =
  AuthenticatedCodesIdValuesRouteImport.update({
    id: '/values',
    path: '/values',
    getParentRoute: () => AuthenticatedCodesIdRoute,
  } as any)
const AuthenticatedAdminTimetablesNewRoute =
  AuthenticatedAdminTimetablesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminTimetablesRoute,
  } as any)
const AuthenticatedAdminTeachersNewRoute =
  AuthenticatedAdminTeachersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminTeachersRoute,
  } as any)
const AuthenticatedAdminStudentsNewRoute =
  AuthenticatedAdminStudentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)
const AuthenticatedAdminRoomsNewRoute =
  AuthenticatedAdminRoomsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminRoomsRoute,
  } as any)
const AuthenticatedCodesIdValuesNewRoute =
  AuthenticatedCodesIdValuesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCodesIdValuesRoute,
  } as any)
const AuthenticatedCodesIdValuesEditValueIdRoute =
  AuthenticatedCodesIdValuesEditValueIdRouteImport.update({
    id: '/edit/$valueId',
    path: '/edit/$valueId',
    getParentRoute: () => AuthenticatedCodesIdValuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/codes': typeof AuthenticatedCodesRouteWithChildren
  '/major-sections': typeof AuthenticatedMajorSectionsRouteWithChildren
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/subjects': typeof AuthenticatedSubjectsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/timetables': typeof AuthenticatedTimetablesRouteWithChildren
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/major-sections': typeof AuthenticatedAdminMajorSectionsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRouteWithChildren
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRouteWithChildren
  '/admin/timetable-change-requests': typeof AuthenticatedAdminTimetableChangeRequestsRoute
  '/admin/timetables': typeof AuthenticatedAdminTimetablesRouteWithChildren
  '/codes/$id': typeof AuthenticatedCodesIdRouteWithChildren
  '/codes/new': typeof AuthenticatedCodesNewRoute
  '/major-sections/new': typeof AuthenticatedMajorSectionsNewRoute
  '/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/students/welcome': typeof AuthenticatedStudentsWelcomeRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/teachers/welcome': typeof AuthenticatedTeachersWelcomeRoute
  '/timetable-change-requests/$id': typeof AuthenticatedTimetableChangeRequestsIdRoute
  '/timetables/combine': typeof AuthenticatedTimetablesCombineRoute
  '/timetables/new': typeof AuthenticatedTimetablesNewRoute
  '/timetable-change-requests/': typeof AuthenticatedTimetableChangeRequestsIndexRoute
  '/admin/rooms/new': typeof AuthenticatedAdminRoomsNewRoute
  '/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/admin/teachers/new': typeof AuthenticatedAdminTeachersNewRoute
  '/admin/timetables/new': typeof AuthenticatedAdminTimetablesNewRoute
  '/codes/$id/values': typeof AuthenticatedCodesIdValuesRouteWithChildren
  '/codes/edit/$id': typeof AuthenticatedCodesEditIdRoute
  '/major-sections/edit/$id': typeof AuthenticatedMajorSectionsEditIdRoute
  '/rooms/edit/$id': typeof AuthenticatedRoomsEditIdRoute
  '/students/edit/$id': typeof AuthenticatedStudentsEditIdRoute
  '/subjects/edit/$id': typeof AuthenticatedSubjectsEditIdRoute
  '/subjects/view/$id': typeof AuthenticatedSubjectsViewIdRoute
  '/teachers/edit/$id': typeof AuthenticatedTeachersEditIdRoute
  '/teachers/timetable/$id': typeof AuthenticatedTeachersTimetableIdRoute
  '/timetables/edit/$id': typeof AuthenticatedTimetablesEditIdRoute
  '/timetables/view/$id': typeof AuthenticatedTimetablesViewIdRoute
  '/codes/$id/values/new': typeof AuthenticatedCodesIdValuesNewRoute
  '/codes/$id/values/edit/$valueId': typeof AuthenticatedCodesIdValuesEditValueIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/codes': typeof AuthenticatedCodesRouteWithChildren
  '/major-sections': typeof AuthenticatedMajorSectionsRouteWithChildren
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/subjects': typeof AuthenticatedSubjectsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/timetables': typeof AuthenticatedTimetablesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/major-sections': typeof AuthenticatedAdminMajorSectionsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRouteWithChildren
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRouteWithChildren
  '/admin/timetable-change-requests': typeof AuthenticatedAdminTimetableChangeRequestsRoute
  '/admin/timetables': typeof AuthenticatedAdminTimetablesRouteWithChildren
  '/codes/$id': typeof AuthenticatedCodesIdRouteWithChildren
  '/codes/new': typeof AuthenticatedCodesNewRoute
  '/major-sections/new': typeof AuthenticatedMajorSectionsNewRoute
  '/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/students/welcome': typeof AuthenticatedStudentsWelcomeRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/teachers/welcome': typeof AuthenticatedTeachersWelcomeRoute
  '/timetable-change-requests/$id': typeof AuthenticatedTimetableChangeRequestsIdRoute
  '/timetables/combine': typeof AuthenticatedTimetablesCombineRoute
  '/timetables/new': typeof AuthenticatedTimetablesNewRoute
  '/timetable-change-requests': typeof AuthenticatedTimetableChangeRequestsIndexRoute
  '/admin/rooms/new': typeof AuthenticatedAdminRoomsNewRoute
  '/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/admin/teachers/new': typeof AuthenticatedAdminTeachersNewRoute
  '/admin/timetables/new': typeof AuthenticatedAdminTimetablesNewRoute
  '/codes/$id/values': typeof AuthenticatedCodesIdValuesRouteWithChildren
  '/codes/edit/$id': typeof AuthenticatedCodesEditIdRoute
  '/major-sections/edit/$id': typeof AuthenticatedMajorSectionsEditIdRoute
  '/rooms/edit/$id': typeof AuthenticatedRoomsEditIdRoute
  '/students/edit/$id': typeof AuthenticatedStudentsEditIdRoute
  '/subjects/edit/$id': typeof AuthenticatedSubjectsEditIdRoute
  '/subjects/view/$id': typeof AuthenticatedSubjectsViewIdRoute
  '/teachers/edit/$id': typeof AuthenticatedTeachersEditIdRoute
  '/teachers/timetable/$id': typeof AuthenticatedTeachersTimetableIdRoute
  '/timetables/edit/$id': typeof AuthenticatedTimetablesEditIdRoute
  '/timetables/view/$id': typeof AuthenticatedTimetablesViewIdRoute
  '/codes/$id/values/new': typeof AuthenticatedCodesIdValuesNewRoute
  '/codes/$id/values/edit/$valueId': typeof AuthenticatedCodesIdValuesEditValueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/codes': typeof AuthenticatedCodesRouteWithChildren
  '/_authenticated/major-sections': typeof AuthenticatedMajorSectionsRouteWithChildren
  '/_authenticated/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRouteWithChildren
  '/_authenticated/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/_authenticated/timetables': typeof AuthenticatedTimetablesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/major-sections': typeof AuthenticatedAdminMajorSectionsRoute
  '/_authenticated/admin/rooms': typeof AuthenticatedAdminRoomsRouteWithChildren
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRouteWithChildren
  '/_authenticated/admin/timetable-change-requests': typeof AuthenticatedAdminTimetableChangeRequestsRoute
  '/_authenticated/admin/timetables': typeof AuthenticatedAdminTimetablesRouteWithChildren
  '/_authenticated/codes/$id': typeof AuthenticatedCodesIdRouteWithChildren
  '/_authenticated/codes/new': typeof AuthenticatedCodesNewRoute
  '/_authenticated/major-sections/new': typeof AuthenticatedMajorSectionsNewRoute
  '/_authenticated/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/students/welcome': typeof AuthenticatedStudentsWelcomeRoute
  '/_authenticated/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/_authenticated/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/_authenticated/teachers/welcome': typeof AuthenticatedTeachersWelcomeRoute
  '/_authenticated/timetable-change-requests/$id': typeof AuthenticatedTimetableChangeRequestsIdRoute
  '/_authenticated/timetables/combine': typeof AuthenticatedTimetablesCombineRoute
  '/_authenticated/timetables/new': typeof AuthenticatedTimetablesNewRoute
  '/_authenticated/timetable-change-requests/': typeof AuthenticatedTimetableChangeRequestsIndexRoute
  '/_authenticated/admin/rooms/new': typeof AuthenticatedAdminRoomsNewRoute
  '/_authenticated/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/_authenticated/admin/teachers/new': typeof AuthenticatedAdminTeachersNewRoute
  '/_authenticated/admin/timetables/new': typeof AuthenticatedAdminTimetablesNewRoute
  '/_authenticated/codes/$id/values': typeof AuthenticatedCodesIdValuesRouteWithChildren
  '/_authenticated/codes/edit/$id': typeof AuthenticatedCodesEditIdRoute
  '/_authenticated/major-sections/edit/$id': typeof AuthenticatedMajorSectionsEditIdRoute
  '/_authenticated/rooms/edit/$id': typeof AuthenticatedRoomsEditIdRoute
  '/_authenticated/students/edit/$id': typeof AuthenticatedStudentsEditIdRoute
  '/_authenticated/subjects/edit/$id': typeof AuthenticatedSubjectsEditIdRoute
  '/_authenticated/subjects/view/$id': typeof AuthenticatedSubjectsViewIdRoute
  '/_authenticated/teachers/edit/$id': typeof AuthenticatedTeachersEditIdRoute
  '/_authenticated/teachers/timetable/$id': typeof AuthenticatedTeachersTimetableIdRoute
  '/_authenticated/timetables/edit/$id': typeof AuthenticatedTimetablesEditIdRoute
  '/_authenticated/timetables/view/$id': typeof AuthenticatedTimetablesViewIdRoute
  '/_authenticated/codes/$id/values/new': typeof AuthenticatedCodesIdValuesNewRoute
  '/_authenticated/codes/$id/values/edit/$valueId': typeof AuthenticatedCodesIdValuesEditValueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/codes'
    | '/major-sections'
    | '/rooms'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/timetables'
    | '/admin/codes'
    | '/admin/dashboard'
    | '/admin/major-sections'
    | '/admin/rooms'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable-change-requests'
    | '/admin/timetables'
    | '/codes/$id'
    | '/codes/new'
    | '/major-sections/new'
    | '/rooms/new'
    | '/students/new'
    | '/students/welcome'
    | '/subjects/new'
    | '/teachers/new'
    | '/teachers/welcome'
    | '/timetable-change-requests/$id'
    | '/timetables/combine'
    | '/timetables/new'
    | '/timetable-change-requests/'
    | '/admin/rooms/new'
    | '/admin/students/new'
    | '/admin/teachers/new'
    | '/admin/timetables/new'
    | '/codes/$id/values'
    | '/codes/edit/$id'
    | '/major-sections/edit/$id'
    | '/rooms/edit/$id'
    | '/students/edit/$id'
    | '/subjects/edit/$id'
    | '/subjects/view/$id'
    | '/teachers/edit/$id'
    | '/teachers/timetable/$id'
    | '/timetables/edit/$id'
    | '/timetables/view/$id'
    | '/codes/$id/values/new'
    | '/codes/$id/values/edit/$valueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/codes'
    | '/major-sections'
    | '/rooms'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/timetables'
    | '/'
    | '/admin/codes'
    | '/admin/dashboard'
    | '/admin/major-sections'
    | '/admin/rooms'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable-change-requests'
    | '/admin/timetables'
    | '/codes/$id'
    | '/codes/new'
    | '/major-sections/new'
    | '/rooms/new'
    | '/students/new'
    | '/students/welcome'
    | '/subjects/new'
    | '/teachers/new'
    | '/teachers/welcome'
    | '/timetable-change-requests/$id'
    | '/timetables/combine'
    | '/timetables/new'
    | '/timetable-change-requests'
    | '/admin/rooms/new'
    | '/admin/students/new'
    | '/admin/teachers/new'
    | '/admin/timetables/new'
    | '/codes/$id/values'
    | '/codes/edit/$id'
    | '/major-sections/edit/$id'
    | '/rooms/edit/$id'
    | '/students/edit/$id'
    | '/subjects/edit/$id'
    | '/subjects/view/$id'
    | '/teachers/edit/$id'
    | '/teachers/timetable/$id'
    | '/timetables/edit/$id'
    | '/timetables/view/$id'
    | '/codes/$id/values/new'
    | '/codes/$id/values/edit/$valueId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/_authenticated/codes'
    | '/_authenticated/major-sections'
    | '/_authenticated/rooms'
    | '/_authenticated/students'
    | '/_authenticated/subjects'
    | '/_authenticated/teachers'
    | '/_authenticated/timetables'
    | '/_authenticated/'
    | '/_authenticated/admin/codes'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/major-sections'
    | '/_authenticated/admin/rooms'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/admin/timetable-change-requests'
    | '/_authenticated/admin/timetables'
    | '/_authenticated/codes/$id'
    | '/_authenticated/codes/new'
    | '/_authenticated/major-sections/new'
    | '/_authenticated/rooms/new'
    | '/_authenticated/students/new'
    | '/_authenticated/students/welcome'
    | '/_authenticated/subjects/new'
    | '/_authenticated/teachers/new'
    | '/_authenticated/teachers/welcome'
    | '/_authenticated/timetable-change-requests/$id'
    | '/_authenticated/timetables/combine'
    | '/_authenticated/timetables/new'
    | '/_authenticated/timetable-change-requests/'
    | '/_authenticated/admin/rooms/new'
    | '/_authenticated/admin/students/new'
    | '/_authenticated/admin/teachers/new'
    | '/_authenticated/admin/timetables/new'
    | '/_authenticated/codes/$id/values'
    | '/_authenticated/codes/edit/$id'
    | '/_authenticated/major-sections/edit/$id'
    | '/_authenticated/rooms/edit/$id'
    | '/_authenticated/students/edit/$id'
    | '/_authenticated/subjects/edit/$id'
    | '/_authenticated/subjects/view/$id'
    | '/_authenticated/teachers/edit/$id'
    | '/_authenticated/teachers/timetable/$id'
    | '/_authenticated/timetables/edit/$id'
    | '/_authenticated/timetables/view/$id'
    | '/_authenticated/codes/$id/values/new'
    | '/_authenticated/codes/$id/values/edit/$valueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetables': {
      id: '/_authenticated/timetables'
      path: '/timetables'
      fullPath: '/timetables'
      preLoaderRoute: typeof AuthenticatedTimetablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/major-sections': {
      id: '/_authenticated/major-sections'
      path: '/major-sections'
      fullPath: '/major-sections'
      preLoaderRoute: typeof AuthenticatedMajorSectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/codes': {
      id: '/_authenticated/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof AuthenticatedCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timetable-change-requests/': {
      id: '/_authenticated/timetable-change-requests/'
      path: '/timetable-change-requests'
      fullPath: '/timetable-change-requests/'
      preLoaderRoute: typeof AuthenticatedTimetableChangeRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetables/new': {
      id: '/_authenticated/timetables/new'
      path: '/new'
      fullPath: '/timetables/new'
      preLoaderRoute: typeof AuthenticatedTimetablesNewRouteImport
      parentRoute: typeof AuthenticatedTimetablesRoute
    }
    '/_authenticated/timetables/combine': {
      id: '/_authenticated/timetables/combine'
      path: '/combine'
      fullPath: '/timetables/combine'
      preLoaderRoute: typeof AuthenticatedTimetablesCombineRouteImport
      parentRoute: typeof AuthenticatedTimetablesRoute
    }
    '/_authenticated/timetable-change-requests/$id': {
      id: '/_authenticated/timetable-change-requests/$id'
      path: '/timetable-change-requests/$id'
      fullPath: '/timetable-change-requests/$id'
      preLoaderRoute: typeof AuthenticatedTimetableChangeRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/welcome': {
      id: '/_authenticated/teachers/welcome'
      path: '/welcome'
      fullPath: '/teachers/welcome'
      preLoaderRoute: typeof AuthenticatedTeachersWelcomeRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/teachers/new': {
      id: '/_authenticated/teachers/new'
      path: '/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof AuthenticatedTeachersNewRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/subjects/new': {
      id: '/_authenticated/subjects/new'
      path: '/new'
      fullPath: '/subjects/new'
      preLoaderRoute: typeof AuthenticatedSubjectsNewRouteImport
      parentRoute: typeof AuthenticatedSubjectsRoute
    }
    '/_authenticated/students/welcome': {
      id: '/_authenticated/students/welcome'
      path: '/welcome'
      fullPath: '/students/welcome'
      preLoaderRoute: typeof AuthenticatedStudentsWelcomeRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/rooms/new': {
      id: '/_authenticated/rooms/new'
      path: '/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof AuthenticatedRoomsNewRouteImport
      parentRoute: typeof AuthenticatedRoomsRoute
    }
    '/_authenticated/major-sections/new': {
      id: '/_authenticated/major-sections/new'
      path: '/new'
      fullPath: '/major-sections/new'
      preLoaderRoute: typeof AuthenticatedMajorSectionsNewRouteImport
      parentRoute: typeof AuthenticatedMajorSectionsRoute
    }
    '/_authenticated/codes/new': {
      id: '/_authenticated/codes/new'
      path: '/new'
      fullPath: '/codes/new'
      preLoaderRoute: typeof AuthenticatedCodesNewRouteImport
      parentRoute: typeof AuthenticatedCodesRoute
    }
    '/_authenticated/codes/$id': {
      id: '/_authenticated/codes/$id'
      path: '/$id'
      fullPath: '/codes/$id'
      preLoaderRoute: typeof AuthenticatedCodesIdRouteImport
      parentRoute: typeof AuthenticatedCodesRoute
    }
    '/_authenticated/admin/timetables': {
      id: '/_authenticated/admin/timetables'
      path: '/admin/timetables'
      fullPath: '/admin/timetables'
      preLoaderRoute: typeof AuthenticatedAdminTimetablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/timetable-change-requests': {
      id: '/_authenticated/admin/timetable-change-requests'
      path: '/admin/timetable-change-requests'
      fullPath: '/admin/timetable-change-requests'
      preLoaderRoute: typeof AuthenticatedAdminTimetableChangeRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rooms': {
      id: '/_authenticated/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/major-sections': {
      id: '/_authenticated/admin/major-sections'
      path: '/admin/major-sections'
      fullPath: '/admin/major-sections'
      preLoaderRoute: typeof AuthenticatedAdminMajorSectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/codes': {
      id: '/_authenticated/admin/codes'
      path: '/admin/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetables/view/$id': {
      id: '/_authenticated/timetables/view/$id'
      path: '/view/$id'
      fullPath: '/timetables/view/$id'
      preLoaderRoute: typeof AuthenticatedTimetablesViewIdRouteImport
      parentRoute: typeof AuthenticatedTimetablesRoute
    }
    '/_authenticated/timetables/edit/$id': {
      id: '/_authenticated/timetables/edit/$id'
      path: '/edit/$id'
      fullPath: '/timetables/edit/$id'
      preLoaderRoute: typeof AuthenticatedTimetablesEditIdRouteImport
      parentRoute: typeof AuthenticatedTimetablesRoute
    }
    '/_authenticated/teachers/timetable/$id': {
      id: '/_authenticated/teachers/timetable/$id'
      path: '/timetable/$id'
      fullPath: '/teachers/timetable/$id'
      preLoaderRoute: typeof AuthenticatedTeachersTimetableIdRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/teachers/edit/$id': {
      id: '/_authenticated/teachers/edit/$id'
      path: '/edit/$id'
      fullPath: '/teachers/edit/$id'
      preLoaderRoute: typeof AuthenticatedTeachersEditIdRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/subjects/view/$id': {
      id: '/_authenticated/subjects/view/$id'
      path: '/view/$id'
      fullPath: '/subjects/view/$id'
      preLoaderRoute: typeof AuthenticatedSubjectsViewIdRouteImport
      parentRoute: typeof AuthenticatedSubjectsRoute
    }
    '/_authenticated/subjects/edit/$id': {
      id: '/_authenticated/subjects/edit/$id'
      path: '/edit/$id'
      fullPath: '/subjects/edit/$id'
      preLoaderRoute: typeof AuthenticatedSubjectsEditIdRouteImport
      parentRoute: typeof AuthenticatedSubjectsRoute
    }
    '/_authenticated/students/edit/$id': {
      id: '/_authenticated/students/edit/$id'
      path: '/edit/$id'
      fullPath: '/students/edit/$id'
      preLoaderRoute: typeof AuthenticatedStudentsEditIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/rooms/edit/$id': {
      id: '/_authenticated/rooms/edit/$id'
      path: '/edit/$id'
      fullPath: '/rooms/edit/$id'
      preLoaderRoute: typeof AuthenticatedRoomsEditIdRouteImport
      parentRoute: typeof AuthenticatedRoomsRoute
    }
    '/_authenticated/major-sections/edit/$id': {
      id: '/_authenticated/major-sections/edit/$id'
      path: '/edit/$id'
      fullPath: '/major-sections/edit/$id'
      preLoaderRoute: typeof AuthenticatedMajorSectionsEditIdRouteImport
      parentRoute: typeof AuthenticatedMajorSectionsRoute
    }
    '/_authenticated/codes/edit/$id': {
      id: '/_authenticated/codes/edit/$id'
      path: '/edit/$id'
      fullPath: '/codes/edit/$id'
      preLoaderRoute: typeof AuthenticatedCodesEditIdRouteImport
      parentRoute: typeof AuthenticatedCodesRoute
    }
    '/_authenticated/codes/$id/values': {
      id: '/_authenticated/codes/$id/values'
      path: '/values'
      fullPath: '/codes/$id/values'
      preLoaderRoute: typeof AuthenticatedCodesIdValuesRouteImport
      parentRoute: typeof AuthenticatedCodesIdRoute
    }
    '/_authenticated/admin/timetables/new': {
      id: '/_authenticated/admin/timetables/new'
      path: '/new'
      fullPath: '/admin/timetables/new'
      preLoaderRoute: typeof AuthenticatedAdminTimetablesNewRouteImport
      parentRoute: typeof AuthenticatedAdminTimetablesRoute
    }
    '/_authenticated/admin/teachers/new': {
      id: '/_authenticated/admin/teachers/new'
      path: '/new'
      fullPath: '/admin/teachers/new'
      preLoaderRoute: typeof AuthenticatedAdminTeachersNewRouteImport
      parentRoute: typeof AuthenticatedAdminTeachersRoute
    }
    '/_authenticated/admin/students/new': {
      id: '/_authenticated/admin/students/new'
      path: '/new'
      fullPath: '/admin/students/new'
      preLoaderRoute: typeof AuthenticatedAdminStudentsNewRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
    '/_authenticated/admin/rooms/new': {
      id: '/_authenticated/admin/rooms/new'
      path: '/new'
      fullPath: '/admin/rooms/new'
      preLoaderRoute: typeof AuthenticatedAdminRoomsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoomsRoute
    }
    '/_authenticated/codes/$id/values/new': {
      id: '/_authenticated/codes/$id/values/new'
      path: '/new'
      fullPath: '/codes/$id/values/new'
      preLoaderRoute: typeof AuthenticatedCodesIdValuesNewRouteImport
      parentRoute: typeof AuthenticatedCodesIdValuesRoute
    }
    '/_authenticated/codes/$id/values/edit/$valueId': {
      id: '/_authenticated/codes/$id/values/edit/$valueId'
      path: '/edit/$valueId'
      fullPath: '/codes/$id/values/edit/$valueId'
      preLoaderRoute: typeof AuthenticatedCodesIdValuesEditValueIdRouteImport
      parentRoute: typeof AuthenticatedCodesIdValuesRoute
    }
  }
}

interface AuthenticatedCodesIdValuesRouteChildren {
  AuthenticatedCodesIdValuesNewRoute: typeof AuthenticatedCodesIdValuesNewRoute
  AuthenticatedCodesIdValuesEditValueIdRoute: typeof AuthenticatedCodesIdValuesEditValueIdRoute
}

const AuthenticatedCodesIdValuesRouteChildren: AuthenticatedCodesIdValuesRouteChildren =
  {
    AuthenticatedCodesIdValuesNewRoute: AuthenticatedCodesIdValuesNewRoute,
    AuthenticatedCodesIdValuesEditValueIdRoute:
      AuthenticatedCodesIdValuesEditValueIdRoute,
  }

const AuthenticatedCodesIdValuesRouteWithChildren =
  AuthenticatedCodesIdValuesRoute._addFileChildren(
    AuthenticatedCodesIdValuesRouteChildren,
  )

interface AuthenticatedCodesIdRouteChildren {
  AuthenticatedCodesIdValuesRoute: typeof AuthenticatedCodesIdValuesRouteWithChildren
}

const AuthenticatedCodesIdRouteChildren: AuthenticatedCodesIdRouteChildren = {
  AuthenticatedCodesIdValuesRoute: AuthenticatedCodesIdValuesRouteWithChildren,
}

const AuthenticatedCodesIdRouteWithChildren =
  AuthenticatedCodesIdRoute._addFileChildren(AuthenticatedCodesIdRouteChildren)

interface AuthenticatedCodesRouteChildren {
  AuthenticatedCodesIdRoute: typeof AuthenticatedCodesIdRouteWithChildren
  AuthenticatedCodesNewRoute: typeof AuthenticatedCodesNewRoute
  AuthenticatedCodesEditIdRoute: typeof AuthenticatedCodesEditIdRoute
}

const AuthenticatedCodesRouteChildren: AuthenticatedCodesRouteChildren = {
  AuthenticatedCodesIdRoute: AuthenticatedCodesIdRouteWithChildren,
  AuthenticatedCodesNewRoute: AuthenticatedCodesNewRoute,
  AuthenticatedCodesEditIdRoute: AuthenticatedCodesEditIdRoute,
}

const AuthenticatedCodesRouteWithChildren =
  AuthenticatedCodesRoute._addFileChildren(AuthenticatedCodesRouteChildren)

interface AuthenticatedMajorSectionsRouteChildren {
  AuthenticatedMajorSectionsNewRoute: typeof AuthenticatedMajorSectionsNewRoute
  AuthenticatedMajorSectionsEditIdRoute: typeof AuthenticatedMajorSectionsEditIdRoute
}

const AuthenticatedMajorSectionsRouteChildren: AuthenticatedMajorSectionsRouteChildren =
  {
    AuthenticatedMajorSectionsNewRoute: AuthenticatedMajorSectionsNewRoute,
    AuthenticatedMajorSectionsEditIdRoute:
      AuthenticatedMajorSectionsEditIdRoute,
  }

const AuthenticatedMajorSectionsRouteWithChildren =
  AuthenticatedMajorSectionsRoute._addFileChildren(
    AuthenticatedMajorSectionsRouteChildren,
  )

interface AuthenticatedRoomsRouteChildren {
  AuthenticatedRoomsNewRoute: typeof AuthenticatedRoomsNewRoute
  AuthenticatedRoomsEditIdRoute: typeof AuthenticatedRoomsEditIdRoute
}

const AuthenticatedRoomsRouteChildren: AuthenticatedRoomsRouteChildren = {
  AuthenticatedRoomsNewRoute: AuthenticatedRoomsNewRoute,
  AuthenticatedRoomsEditIdRoute: AuthenticatedRoomsEditIdRoute,
}

const AuthenticatedRoomsRouteWithChildren =
  AuthenticatedRoomsRoute._addFileChildren(AuthenticatedRoomsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedStudentsWelcomeRoute: typeof AuthenticatedStudentsWelcomeRoute
  AuthenticatedStudentsEditIdRoute: typeof AuthenticatedStudentsEditIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedStudentsWelcomeRoute: AuthenticatedStudentsWelcomeRoute,
  AuthenticatedStudentsEditIdRoute: AuthenticatedStudentsEditIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedSubjectsRouteChildren {
  AuthenticatedSubjectsNewRoute: typeof AuthenticatedSubjectsNewRoute
  AuthenticatedSubjectsEditIdRoute: typeof AuthenticatedSubjectsEditIdRoute
  AuthenticatedSubjectsViewIdRoute: typeof AuthenticatedSubjectsViewIdRoute
}

const AuthenticatedSubjectsRouteChildren: AuthenticatedSubjectsRouteChildren = {
  AuthenticatedSubjectsNewRoute: AuthenticatedSubjectsNewRoute,
  AuthenticatedSubjectsEditIdRoute: AuthenticatedSubjectsEditIdRoute,
  AuthenticatedSubjectsViewIdRoute: AuthenticatedSubjectsViewIdRoute,
}

const AuthenticatedSubjectsRouteWithChildren =
  AuthenticatedSubjectsRoute._addFileChildren(
    AuthenticatedSubjectsRouteChildren,
  )

interface AuthenticatedTeachersRouteChildren {
  AuthenticatedTeachersNewRoute: typeof AuthenticatedTeachersNewRoute
  AuthenticatedTeachersWelcomeRoute: typeof AuthenticatedTeachersWelcomeRoute
  AuthenticatedTeachersEditIdRoute: typeof AuthenticatedTeachersEditIdRoute
  AuthenticatedTeachersTimetableIdRoute: typeof AuthenticatedTeachersTimetableIdRoute
}

const AuthenticatedTeachersRouteChildren: AuthenticatedTeachersRouteChildren = {
  AuthenticatedTeachersNewRoute: AuthenticatedTeachersNewRoute,
  AuthenticatedTeachersWelcomeRoute: AuthenticatedTeachersWelcomeRoute,
  AuthenticatedTeachersEditIdRoute: AuthenticatedTeachersEditIdRoute,
  AuthenticatedTeachersTimetableIdRoute: AuthenticatedTeachersTimetableIdRoute,
}

const AuthenticatedTeachersRouteWithChildren =
  AuthenticatedTeachersRoute._addFileChildren(
    AuthenticatedTeachersRouteChildren,
  )

interface AuthenticatedTimetablesRouteChildren {
  AuthenticatedTimetablesCombineRoute: typeof AuthenticatedTimetablesCombineRoute
  AuthenticatedTimetablesNewRoute: typeof AuthenticatedTimetablesNewRoute
  AuthenticatedTimetablesEditIdRoute: typeof AuthenticatedTimetablesEditIdRoute
  AuthenticatedTimetablesViewIdRoute: typeof AuthenticatedTimetablesViewIdRoute
}

const AuthenticatedTimetablesRouteChildren: AuthenticatedTimetablesRouteChildren =
  {
    AuthenticatedTimetablesCombineRoute: AuthenticatedTimetablesCombineRoute,
    AuthenticatedTimetablesNewRoute: AuthenticatedTimetablesNewRoute,
    AuthenticatedTimetablesEditIdRoute: AuthenticatedTimetablesEditIdRoute,
    AuthenticatedTimetablesViewIdRoute: AuthenticatedTimetablesViewIdRoute,
  }

const AuthenticatedTimetablesRouteWithChildren =
  AuthenticatedTimetablesRoute._addFileChildren(
    AuthenticatedTimetablesRouteChildren,
  )

interface AuthenticatedAdminRoomsRouteChildren {
  AuthenticatedAdminRoomsNewRoute: typeof AuthenticatedAdminRoomsNewRoute
}

const AuthenticatedAdminRoomsRouteChildren: AuthenticatedAdminRoomsRouteChildren =
  {
    AuthenticatedAdminRoomsNewRoute: AuthenticatedAdminRoomsNewRoute,
  }

const AuthenticatedAdminRoomsRouteWithChildren =
  AuthenticatedAdminRoomsRoute._addFileChildren(
    AuthenticatedAdminRoomsRouteChildren,
  )

interface AuthenticatedAdminStudentsRouteChildren {
  AuthenticatedAdminStudentsNewRoute: typeof AuthenticatedAdminStudentsNewRoute
}

const AuthenticatedAdminStudentsRouteChildren: AuthenticatedAdminStudentsRouteChildren =
  {
    AuthenticatedAdminStudentsNewRoute: AuthenticatedAdminStudentsNewRoute,
  }

const AuthenticatedAdminStudentsRouteWithChildren =
  AuthenticatedAdminStudentsRoute._addFileChildren(
    AuthenticatedAdminStudentsRouteChildren,
  )

interface AuthenticatedAdminTeachersRouteChildren {
  AuthenticatedAdminTeachersNewRoute: typeof AuthenticatedAdminTeachersNewRoute
}

const AuthenticatedAdminTeachersRouteChildren: AuthenticatedAdminTeachersRouteChildren =
  {
    AuthenticatedAdminTeachersNewRoute: AuthenticatedAdminTeachersNewRoute,
  }

const AuthenticatedAdminTeachersRouteWithChildren =
  AuthenticatedAdminTeachersRoute._addFileChildren(
    AuthenticatedAdminTeachersRouteChildren,
  )

interface AuthenticatedAdminTimetablesRouteChildren {
  AuthenticatedAdminTimetablesNewRoute: typeof AuthenticatedAdminTimetablesNewRoute
}

const AuthenticatedAdminTimetablesRouteChildren: AuthenticatedAdminTimetablesRouteChildren =
  {
    AuthenticatedAdminTimetablesNewRoute: AuthenticatedAdminTimetablesNewRoute,
  }

const AuthenticatedAdminTimetablesRouteWithChildren =
  AuthenticatedAdminTimetablesRoute._addFileChildren(
    AuthenticatedAdminTimetablesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCodesRoute: typeof AuthenticatedCodesRouteWithChildren
  AuthenticatedMajorSectionsRoute: typeof AuthenticatedMajorSectionsRouteWithChildren
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRouteWithChildren
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRouteWithChildren
  AuthenticatedTimetablesRoute: typeof AuthenticatedTimetablesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminMajorSectionsRoute: typeof AuthenticatedAdminMajorSectionsRoute
  AuthenticatedAdminRoomsRoute: typeof AuthenticatedAdminRoomsRouteWithChildren
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRouteWithChildren
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRouteWithChildren
  AuthenticatedAdminTimetableChangeRequestsRoute: typeof AuthenticatedAdminTimetableChangeRequestsRoute
  AuthenticatedAdminTimetablesRoute: typeof AuthenticatedAdminTimetablesRouteWithChildren
  AuthenticatedTimetableChangeRequestsIdRoute: typeof AuthenticatedTimetableChangeRequestsIdRoute
  AuthenticatedTimetableChangeRequestsIndexRoute: typeof AuthenticatedTimetableChangeRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCodesRoute: AuthenticatedCodesRouteWithChildren,
  AuthenticatedMajorSectionsRoute: AuthenticatedMajorSectionsRouteWithChildren,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRouteWithChildren,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRouteWithChildren,
  AuthenticatedTimetablesRoute: AuthenticatedTimetablesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminMajorSectionsRoute: AuthenticatedAdminMajorSectionsRoute,
  AuthenticatedAdminRoomsRoute: AuthenticatedAdminRoomsRouteWithChildren,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRouteWithChildren,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRouteWithChildren,
  AuthenticatedAdminTimetableChangeRequestsRoute:
    AuthenticatedAdminTimetableChangeRequestsRoute,
  AuthenticatedAdminTimetablesRoute:
    AuthenticatedAdminTimetablesRouteWithChildren,
  AuthenticatedTimetableChangeRequestsIdRoute:
    AuthenticatedTimetableChangeRequestsIdRoute,
  AuthenticatedTimetableChangeRequestsIndexRoute:
    AuthenticatedTimetableChangeRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
